FROM openshift/origin-release:golang-1.11 AS build
WORKDIR /go/src/github.com/vmware-tanzu/velero-plugin-for-microsoft-azure
# copy vendor in separately so the layer can be cached if the contents don't change
COPY vendor vendor
COPY velero-plugin-for-microsoft-azure velero-plugin-for-microsoft-azure
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /go/bin/velero-plugin-for-microsoft-azure ./velero-plugin-for-microsoft-azure


FROM registry.access.redhat.com/ubi8-minimal
RUN mkdir /plugins
COPY --from=build /go/bin/velero-plugin-for-microsoft-azure /plugins/
USER nobody:nobody
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]
